Repository ungdev/UA-front, pull requests merged in 2022-09, with the labels that each got.

#214 Update graphics and text for UA 2022
  public/Nunito-Regular.ttf
  public/UA_Title.ttf
  public/background.jpg
  public/favicon.ico
  public/fonts/Kanit.ttf
  public/fonts/LemonMilk.ttf
  public/logo-notext.png
  public/logo.png
  public/tournaments/lol-leisure.jpg
  public/tournaments/lol.jpg
  public/tournaments/open.jpg
  public/tournaments/rocket-league.jpg
  public/tournaments/ssbu.jpg
  public/tournaments/tft.jpg
  public/tournaments/valorant.jpg
  src/components/Header.jsx
  src/components/Header.scss
  src/components/LoginModal.jsx
  src/components/Navbar.jsx
  src/components/Navbar.scss
  src/components/PanelHeader.scss
  src/components/TournamentCards.jsx
  src/components/TournamentCards.scss
  src/components/UI/Button.jsx
  src/components/UI/Button.scss
  src/components/UI/Card.jsx
  src/components/UI/Card.scss
  src/components/UI/Divider.jsx
  src/components/UI/Divider.scss
  src/components/UI/LogoSVG.jsx
  src/components/UI/Modal.jsx
  src/components/UI/Modal.scss
  src/components/UI/Table.jsx
  src/components/UI/Table.scss
  src/components/UI/Title.jsx
  src/components/UI/Title.scss
  src/components/UI/index.js
  src/global.scss
  src/pages/_app.jsx
  src/pages/contact.jsx
  src/pages/faq.jsx
  src/pages/index.jsx
  src/pages/index.scss
  src/pages/information.jsx
  src/pages/information.scss
  src/pages/legal.jsx
  src/styles.scss
  src/utils/tournaments.jsx
  src/variables.scss
  yarn.lock
Labels: site vitrine

#213 During password resetting, if passwords didn't match, it was still changed
  src/components/ResetModal.jsx
Labels: fix, dashboard

#212 fix : some POST requests could be sent with header Content-Type=application/x-www-form-urlencoded
  src/pages/faq.jsx
  src/utils/api.js
Labels: fix
